### ISSUE TITLE
Syntax error in client/actor.go

### ISSUE THREAD

**Issue by zillolo** [ethicatech/tinybiome#10]
Executing
```
    go run node/tbnode.go
```
results in the following error:
```
client/actor.go:644: syntax error: unexpected range, expecting {
client/actor.go:651: syntax error: unexpected }
```
with golang version:
```
go version go1.3.3 linux/amd64
```

**Comment by dantoye** [comment]
Try go 1.4. This is the change that broke it: https://golang.org/doc/go1.4#forrange

You can fix it for 1.3 by changing the line 644 to "for _ = range [6]byte{}"

There may be other compiler issues using 1.3
